### ISSUE TITLE
URL of signing key has changed

### ISSUE THREAD

**Issue by rGunti** [buluma/ansible-role-influxdb2#40]
# Describe the bug

The URL of the signing key has changed:

```diff
- https://repos.influxdata.com/influxdb-archive.key
+ https://repos.influxdata.com/influxdata-archive.key
```

Sourced from: https://docs.influxdata.com/influxdb/v2/install/?t=Linux#install-influxdb-as-a-service-with-systemd

This issue is not blocking as the key can be overwritten like so:

```yaml
- name: "Install InfluxDB"
  hosts: "influxdb"
  become: true
  roles:
    - role: buluma.influxdb2
      influxdb_signing_key: https://repos.influxdata.com/influxdata-archive.key
```

## Playbook

Please paste the playbook you are using. (Consider `requirements.yml` and
optionally the command you've invoked.)

```yaml
---
- name: "Install InfluxDB"
  hosts: "influxdb"
  become: true
  roles:
    - role: buluma.influxdb2
```

## Output

```
TASK [buluma.influxdb2 : setup | Add InfluxData's key] *******************************************************************************************************************
fatal: [10.45.10.123]: FAILED! => {"changed": false, "msg": "Failed to download key at https://repos.influxdata.com/influxdb-archive.key: HTTP Error 404: Not Found"}
```

## Environment

- Control node OS: macOS 15
- Control node Ansible version: 2.17.6
- Managed node OS: Debian 12
